server:
  port: ${APPLICATION_PORT}

spring:
  application:
    name: 'auth-service'

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test

  jackson:
    locale: en_US

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: 'ru.moonlightapp.backend.core.storage.dialect.CustomH2Dialect'

    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: moonlight.mail.agent
    password: '${GMAIL_APP_PASSWORD}'
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
    test-connection: true

  main:
    banner-mode: off

  profiles:
    active: ${ACTIVE_PROFILES}

  sql:
    init:
      mode: always

  web:
    locale: en_US