server:
  port: ${APPLICATION_PORT}

  jwt:
    secret: '${JWT_SECRET}'
    lifetime:
      access-token: 43200     # 12 hours -> seconds
      refresh-token: 2592000  # 30 days -> seconds

  error:
    whitelabel:
      enabled: false
    path: /error

  mail:
    name: 'Moonlight App'
    address: moonlight.mail.agent@gmail.com

  servlet:
    session:
      cookie:
        name: 'mlsession'
        same-site: lax

spring:
  application:
    name: 'auth-service'

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test

  jackson:
    locale: en_US

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: 'ru.moonlightapp.backend.core.storage.dialect.CustomH2Dialect'

    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: moonlight.mail.agent
    password: '${GMAIL_APP_PASSWORD}'
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
    test-connection: true

  main:
    banner-mode: off

  profiles:
    active: ${ACTIVE_PROFILES}

  sql:
    init:
      mode: always

  web:
    locale: en_US

grpc:
  server:
    port: 9091
