spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: moonlight.mail.agent
    password: '${GMAIL_APP_PASSWORD}'
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
    test-connection: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 4MB

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    '[org.springframework.security]': DEBUG
    '[org.springframework.web]': DEBUG
  pattern:
    console: '%clr([){faint}%clr(%d{dd.MM.yy}){faint} %clr(%d{HH:mm:ss}){magenta}%clr(]){faint} %clr(%5p) %clr(:){faint} %clr(%-40.40logger{0}){cyan} %clr(:){faint} %m%n%wEx'

server:
  cors:
    allowed-origin: 'http://localhost:8080'

  jwt:
    secret: '${JWT_SECRET}'
    lifetime:
      access-token: 43200     # 12 hours -> seconds
      refresh-token: 2592000  # 30 days -> seconds

  error:
    whitelabel:
      enabled: false
    path: /error

  host: http://localhost:8080

  mail:
    name: 'Moonlight App'
    address: moonlight.mail.agent@gmail.com

  servlet:
    session:
      cookie:
        name: 'mlsession'
        same-site: lax

springdoc:
  api-docs:
    path: '/docs/openapi'
    version: openapi_3_1
  default-produces-media-type: 'application/json'
  enable-spring-security: false
  swagger-ui:
    operations-sorter: alpha
    use-root-path: true