server:
  port: ${APPLICATION_PORT}

  error:
    whitelabel:
      enabled: false
    path: /error

  host: http://localhost:8080

  servlet:
    session:
      cookie:
        name: 'mlsession'
        same-site: lax

spring:
  application:
    name: 'user-content-service'

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test

  jackson:
    locale: en_US

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: 'ru.moonlightapp.backend.core.storage.dialect.CustomH2Dialect'

    open-in-view: false

  main:
    banner-mode: off

  profiles:
    active: ${ACTIVE_PROFILES}

  sql:
    init:
      mode: always

  web:
    locale: en_US

grpc:
  server:
    port: 9092